/*const env = {
  ROOT: "dist/css/",
  CSSDIRECTORY: 'dist/css/',
  ROUTEPATH: '/',
  ENVIRONMENT: 'DEVELOPMENT',
  WEBSERVERADDRESS: "index.html",
  SAVEAPPLICATIONMODULE: "PO_INTERRUPCIONES_DESA_v2",
  SAVEAPPLICATIONNAME: 'REACT_INTERRUPCIONES_WEB_DESA_v2'
}
*/

const env = {
  ROOT: "css/",
  CSSDIRECTORY: 'css/',
  ROUTEPATH: 'index.html',
  ENVIRONMENT: 'PRODUCTION',
  WEBSERVERADDRESS: "http://gisred.chilquinta/AP/",
  SAVEAPPLICATIONMODULE: "PO_INTERRUPCIONES_PROD_v2",
  SAVEAPPLICATIONNAME: 'REACT_INTERRUPCIONES_WEB_PROD_V2'
}


export default env;
